### DISCUSSION TITLE
my ore doesnt generates.I use paper 1.120

### DISCUSSION THREAD

**Discussion by ofek111** [DerFrZocker/Custom-Ore-Generator#27] [Q&A]
[ruby.json](https://github.com/DerFrZocker/Custom-Ore-Generator/files/12868800/ruby.json)

**Comment by ofek111** [comment]
# Only edit this file if you 10000% sure you know what you are doing. 
# You can set everything via the plugin commands, no need to edit this file manully.

value:
  ==: CustomOreGenerator#OreConfig
  name: ruby
  material: NOTE_BLOCK
  ore-generator: VANILLA_MINABLE_GENERATOR
  block-selector: COUNT_RANGE
  activated: true
  generated-all: false
  biomes:
  - FROZEN_OCEAN
  - DEEP_OCEAN
  - SWAMP
  - SPARSE_JUNGLE
  - FROZEN_RIVER
  - SNOWY_TAIGA
  - PLAINS
  - MANGROVE_SWAMP
  - BEACH
  - DESERT
  - JUNGLE
  - MUSHROOM_FIELDS
  - BIRCH_FOREST
  - FOREST
  - WINDSWEPT_HILLS
  - RIVER
  - TAIGA
  - OCEAN
  custom-data:
    ORAXEN: ruby_ore
  ore-generator-settings:
    ==: CustomOreGenerator#OreSettingsContainer
    ore-settings:
      VEIN_SIZE: 20.0
  block-selector-settings:
    ==: CustomOreGenerator#OreSettingsContainer
    ore-settings:
      VEINS_PER_CHUNK: 12.0
      HEIGHT_RANGE: 50.0
      MINIMUM_HEIGHT: -50.0

**Comment by DerFrZocker** [comment]
You are missing which blocks should get replaced.
Since you want to generate it between -50 and 0 you probably want to add deepslate.

```yml
# Only edit this file if you 10000% sure you know what you are doing. 
# You can set everything via the plugin commands, no need to edit this file manully.

value:
  ==: CustomOreGenerator#OreConfig
  name: ruby
  material: NOTE_BLOCK
  ore-generator: VANILLA_MINABLE_GENERATOR
  block-selector: COUNT_RANGE
  activated: true
  generated-all: false
  replace-materials:
  - DEEPSLATE
  biomes:
  - FROZEN_OCEAN
  - DEEP_OCEAN
  - SWAMP
  - SPARSE_JUNGLE
  - FROZEN_RIVER
  - SNOWY_TAIGA
  - PLAINS
  - MANGROVE_SWAMP
  - BEACH
  - DESERT
  - JUNGLE
  - MUSHROOM_FIELDS
  - BIRCH_FOREST
  - FOREST
  - WINDSWEPT_HILLS
  - RIVER
  - TAIGA
  - OCEAN
  custom-data:
    ORAXEN: ruby_ore
  ore-generator-settings:
    ==: CustomOreGenerator#OreSettingsContainer
    ore-settings:
      VEIN_SIZE: 20.0
  block-selector-settings:
    ==: CustomOreGenerator#OreSettingsContainer
    ore-settings:
      VEINS_PER_CHUNK: 12.0
      HEIGHT_RANGE: 50.0
      MINIMUM_HEIGHT: -50.0
```
