### ISSUE TITLE
Server Crash When Using Oraxen Ores

### ISSUE THREAD

**Issue by DerFrZocker** [DerFrZocker/Custom-Ore-Generator#26]
### Discussed in https://github.com/DerFrZocker/Custom-Ore-Generator/discussions/25

<div type='discussions-op-text'>

<sup>Originally posted by **Cokenpizza** September 10, 2023</sup>
When using Oraxen blocks, the server crashes immediately upon loading any new chunks.  I originally believed this to be an issue with other plugins, but even running a test server with only Oraxen and Custom-Ore-Generator causes the crashes.

Minecraft 1.20.1 Paper 1.20.1-171
Oraxen-1.161.0
Custom-Ore-Generator v2023.07.9 (also tried the Dev version which appears to be the same and still crashes)

Crash Log: https://mclo.gs/tRmwPcl
Latest Log: https://mclo.gs/Pb697iF

Here are a couple of my configs, made using the in-game menu.  One for the End and one for the Nether.  Both crash when running through the dimension.

```
value:
  ==: CustomOreGenerator#OreConfig
  name: EndEmeraldOre
  material: NOTE_BLOCK
  ore-generator: SINGLE_ORE_GENERATOR
  block-selector: HIGHEST_BLOCK
  activated: true
  generated-all: false
  biomes:
  - THE_END
  - END_BARRENS
  - END_MIDLANDS
  - SMALL_END_ISLANDS
  - END_HIGHLANDS
  replace-materials:
  - END_STONE
  custom-data:
    ORAXEN: end_emerald_ore
  block-selector-settings:
    ==: CustomOreGenerator#OreSettingsContainer
    ore-settings:
      VEINS_PER_CHUNK: 3.0
```
```
value:
  ==: CustomOreGenerator#OreConfig
  name: NetherEmeraldOre
  material: NOTE_BLOCK
  ore-generator: SINGLE_ORE_GENERATOR
  block-selector: COUNT_RANGE
  activated: true
  generated-all: false
  biomes:
  - CRIMSON_FOREST
  - SOUL_SAND_VALLEY
  - NETHER_WASTES
  - BASALT_DELTAS
  - WARPED_FOREST
  replace-materials:
  - NETHERRACK
  custom-data:
    ORAXEN: nether_emerald_ore
  block-selector-settings:
    ==: CustomOreGenerator#OreSettingsContainer
    ore-settings:
      VEINS_PER_CHUNK: 3.0
      MINIMUM_HEIGHT: 1.0
      HEIGHT_RANGE: 191.0
```</div>
