### ISSUE TITLE
Not detecting biomes correctly

### ISSUE THREAD

**Issue by robertosu** [DerFrZocker/Custom-Ore-Generator#42]
The plugin is not generating ores in some biomes that are present on the server, it throws these exceptions in console.  As we can see in the image with x-ray, no custom ores are generated in deep dark biome. 

Im using dev build #83 on paper last 1.21.1 build

![image](https://github.com/user-attachments/assets/1cbcbaee-2835-4010-b216-ccfdd56f2c72)
![image](https://github.com/user-attachments/assets/71681a0a-e962-4ef0-8fc5-36a4b19fb07e)

**Comment by DerFrZocker** [comment]
This looks like a malformatted ore config.
Can you provide the `alboris` ore config? It should be located under `{server-directory}/plugins/custom-ore-generator/data/ore-config`

**Comment by robertosu** [comment]
It was indeed a malformed config (my fault i think), but through some testing I found that the custom blocks were not being generated in 'deep dark'.

Steps to reproduce:

Do '/oregen create' and the normal procedure for oraxen blocks, select deep dark biome, and in this case I selected bamboo_jungle to see if it works.

No blocks are created in deep dark, but they are created in bamboo_jungle.


ore-config file:
```
value:
  ==: CustomOreGenerator#OreConfig
  name: orax
  material: NOTE_BLOCK
  ore-generator: VANILLA_MINABLE_GENERATOR
  block-selector: COUNT_RANGE
  activated: true
  generated-all: false
  biomes:
  - DEEP_DARK
  - STONY_PEAKS
  - BAMBOO_JUNGLE
  replace-materials:
  - DEEPSLATE
  custom-data:
    ORAXEN: orax_ore
  ore-generator-settings:
    ==: CustomOreGenerator#OreSettingsContainer
    ore-settings:
      VEIN_SIZE: 8.0
  block-selector-settings:
    ==: CustomOreGenerator#OreSettingsContainer
    ore-settings:
      MINIMUM_HEIGHT: -62.0
      VEINS_PER_CHUNK: 7.0
      HEIGHT_RANGE: 64.0
```
Screenshots:
![image](https://github.com/user-attachments/assets/248195e5-9fb1-451b-bd9a-9c59f47bfb4c)
![image](https://github.com/user-attachments/assets/03b90897-f3cc-4cf3-97b5-dd7ffcaf1a82)
