### ISSUE TITLE
No new ore is generated from Oraxen | 1.21.3

### ISSUE THREAD

**Issue by KLOFFFF** [DerFrZocker/Custom-Ore-Generator#45]
I ran into a problem when using the Custom Ore Generator plugins version 2024.12.24 and Oraxen version 1.186.1 in conjunction with Minecraft version 1.21.3 (with plans to upgrade to 1.21.4). The essence of the problem is that the new ore that I tried to create using the Custom Ore Generator plugin is not displayed in either the new or the existing worlds. 

file: **custom-ore-generator/data/ore-config/orax_ore.yml**
```
# Only edit this file if you 10000% sure you know what you are doing. 
# You can set everything via the plugin commands, no need to edit this file manully.

value:
  ==: CustomOreGenerator#OreConfig
  name: orax_ore
  material: NOTE_BLOCK
  ore-generator: VANILLA_MINABLE_GENERATOR
  block-selector: COUNT_RANGE
  activated: true
  generated-all: false
  biomes:
  - FROZEN_OCEAN
  - SAVANNA_PLATEAU
  - TAIGA
  - SAVANNA
  - SWAMP
  - DRIPSTONE_CAVES
  - ICE_SPIKES
  - FROZEN_PEAKS
  - LUSH_CAVES
  - DARK_FOREST
  - OLD_GROWTH_SPRUCE_TAIGA
  - FROZEN_RIVER
  - LUKEWARM_OCEAN
  - MUSHROOM_FIELDS
  - WARM_OCEAN
  - FOREST
  - WINDSWEPT_FOREST
  - DEEP_OCEAN
  - SUNFLOWER_PLAINS
  - STONY_PEAKS
  - STONY_SHORE
  - FLOWER_FOREST
  - DEEP_LUKEWARM_OCEAN
  - OLD_GROWTH_BIRCH_FOREST
  - DESERT
  - SNOWY_TAIGA
  - BEACH
  - GROVE
  - DEEP_FROZEN_OCEAN
  - RIVER
  - OLD_GROWTH_PINE_TAIGA
  - DEEP_COLD_OCEAN
  - WINDSWEPT_GRAVELLY_HILLS
  - SNOWY_PLAINS
  - JAGGED_PEAKS
  - ERODED_BADLANDS
  - BAMBOO_JUNGLE
  - PLAINS
  - MEADOW
  - SNOWY_BEACH
  - SPARSE_JUNGLE
  - JUNGLE
  - SNOWY_SLOPES
  - BIRCH_FOREST
  - OCEAN
  - MANGROVE_SWAMP
  - COLD_OCEAN
  - BADLANDS
  - WINDSWEPT_HILLS
  - WOODED_BADLANDS
  - WINDSWEPT_SAVANNA
  replace-materials:
  - STONE
  custom-data:
    ORAXEN: orax_ore
  ore-generator-settings:
    ==: CustomOreGenerator#OreSettingsContainer
    ore-settings:
      VEIN_SIZE: 2.0
  block-selector-settings:
    ==: CustomOreGenerator#OreSettingsContainer
    ore-settings:
      MINIMUM_HEIGHT: 0.0
      VEINS_PER_CHUNK: 6.0
      HEIGHT_RANGE: 10.0
```

file: **custom-ore-generator/data/world-config/world.yml**
```
# Only edit this file if you 10000% sure you know what you are doing. 
# You can set everything via the plugin commands, no need to edit this file manully.

value:
  ==: CustomOreGenerator#WorldConfig
  name: world
  ore-config:
  - orax_ore
  - amethyst_ore
```
> [!NOTE]
> Plugins: Custom Ore Generator, Oraxen
>
